### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by alexanderadam** [opthomas-prime/xmpp-webhook#5]
Hi Thomas,

it would be nice if there would be an official Docker image for XMPP webhook.

PS: Thank you for your work!

**Comment by opthomas-prime** [comment]
https://github.com/opthomas-prime/xmpp-webhook/issues/6

**Comment by alexanderadam** [comment]
Would it be okay for you to keep this issue open until the issue is actually fixed? :wink:

**Comment by opthomas-prime** [comment]
Yes, we can keep it open. The Dockerfile for the production image is not the problem here... This only makes sense if we are able to start a dev environment aswell. Which means we should be able to spin-up a XMPP server aswell (and maybe some default message sourcecs aswell).

**Comment by alexanderadam** [comment]
> This only makes sense if we are able to start a dev environment aswell. Which means we should be able to spin-up a XMPP server aswell (and maybe some default message sourcecs).

You would usually use [`docker-compose`](https://docs.docker.com/compose/) for development, wouldn't you?
And there are various example available already (i.e. [these](https://github.com/search?q=%22image%3A+ejabberd%2Fecs%22+filename%3Adocker-compose.yml+language%3AYAML&type=Code) or [these](https://github.com/search?l=&q=%22image%3A+prosody%2Fprosody%22+filename%3Adocker-compose.yml+language%3AYAML&type=Code)).

Then you just would just have to extend the `docker-compose.yml` with the `xmpp-webhook` image. 
So you would probably add something like:

```yaml
  webhook:
    image: xmpp-webhook/xmpp-webhook
    ports:
      - '3000:3000'
    environment:
      - XMPP_ID=foo@example.org
      - XMPP_PASS=secret
      - XMPP_RECEIVERS=bar@example.org
```

or `build: .` instead `image: xmpp-webhook/xmpp-webhook` if you want to build the local data.
